# Generated by Django 6.1 on 2026-09-06 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickethistory',
            options={},
        ),
        migrations.RenameField(
            model_name='tickethistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='requester_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sla_due_at',
        ),
        migrations.AddField(
            model_name='slaalert',
            name='alert_type',
            field=models.CharField(default='INFO', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_paused_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
